const fs = require('fs');
const path = require('path');

const weaponsFolder = 'C:/weapons';

const ITEM_NAMES = [
    'Wolf Arrows',
    'Venom Arrow',
    'Grenade',
    'Steady Arrow',
    'Hatchet',
    'Bone Edge',
    'Stone Slicer',
    'Halbard',
    'Hate\'s Hand',
    'Steel Axe',
    'Simple Hatchet',
    'Volcano Axe',
    'Heavy Hitter',
    'Basic Axe',
    'Basic Pick',
    'Cleaver',
    'Rune Axe',
    'Throwing Axe',
    'Mystic Axe',
    'Bat Wing Axe',
    'Stone Hatchet',
    'Warrior\'s Axe',
    'Hunter\'s Axe',
    'Emerald Throwing Axe',
    'Simple Bow',
    'Stone Bow',
    'Teak Bow',
    'Elven Bow',
    'Yew Bow',
    'Bone Brawler',
    'Stone Brawler',
    'Brass Brawler',
    'Steel Brawler',
    'Diamond Slicer',
    'Bone Shiv',
    'Steel Claw',
    'Royal Shiv',
    'Face Melter',
    'Burglar\'s Bruiser',
    'Spotted Mace',
    'Headache',
    'Hell Snowball',
    'Temple Tickler',
    'Skull Crusher',
    'Heavy Hitter',
    'Ball and Chain',
    'Simple Flail',
    'Human Cleaver',
    'Blunt Instrument',
    'Simple Crossbow',
    'Bronze Crossbow',
    'Fallen Angel',
    'Ballista',
    'Simple Dagger',
    'Spleen Tickler',
    'Gut Slicer',
    'Simple Shiv',
    'Bone Slicer',
    'Bat Dagger',
    'Fat Dagger',
    'Basic Dagger',
    'Throwing Knife',
    'Crescent Moon',
    'Catholic Needle',
    'Impractical Dagger',
    'Rough Tide',
    'Jungle Dagger',
    'Steel Dagger',
    'Kidney Carver',
    'Bronze Dagger',
    'Knight\'s Knife',
    'Basic Shotgun',
    'Hand Cannon',
    'Noob Tube',
    'Death Funnel',
    'Pirate Blaster',
    'Gentleman\'s Pistol',
    'Ornate Pistol',
    'Fancy Cannon',
    'Stone Hammer',
    'Blunt Hammer',
    'Purple Mallet',
    'Crude Hammer',
    'Gilded Whacker',
    'Stone Whacker',
    'Precise Death',
    'Brick Hammer',
    'Onyx Hammer',
    'Ornate Hammer',
    'Heavy Hammer',
    'Golden Hammer',
    'Wooden Mallet',
    'Simple Pike',
    'Fish Gutter',
    'Spine Tickler',
    'Ice Halberd',
    'Trident',
    'Agile Death',
    'Death\'s Hand',
    'Fire Pike',
    'Basic Staff',
    'Teak Staff',
    'Blunt Staff',
    'Ocean\'s Fury',
    'Wizard\'s Walker',
    'Jungle\'s Grasp',
    'Blood Orb Staff',
    'Void Staff',
    'Nature\'s Birth',
    'Watchful Staff',
    'Shaman\'s Stick',
    'Cardinal\'s Staff',
    'Gilded Sword',
    'Sparring Sword',
    'Onxy Hilt',
    'Bat Sword',
    'Neck Slicer',
    'Royal Blade',
    'Knight\'s Sword',
    'Fatty Sword',
    'Scimitar',
    'Tummy Tickler',
    'Void Sword',
    'Void Katana',
    'Quick Sword',
    'Gut Ripper',
    'Onyx Throwing Knife',
    'Broad Sword',
    'Kukri',
    'Ancient Sword',
    'Light Sword',
    'Ornamental Sword',
    'Bastard Blade',
    'Mine',
    'Shuriken',
    'Smoke Bomb',
    'Ninjy Star',
    'Ninjy Shiv',
]

const folders = fs.readdirSync(weaponsFolder).map(fileName=>{
    return path.join(weaponsFolder, fileName);
});

const fileNames = folders.map(folderName=>{
    return fs.readdirSync(folderName);
}).flat();

let moneyPerSecond = 10;

let itemData = fileNames.map((fileName,idx)=>{
    return {
        itemName:ITEM_NAMES[idx],
        moneyPerSecond: moneyPerSecond += Math.trunc(moneyPerSecond*0.15),
        img:`/imgs/${fileName}` 
    }
});

itemData.unshift({
    itemName: 'Empty',
    moneyPerSecond:0,
    img:null
});

let data = JSON.stringify(itemData);

fs.writeFileSync('item-data.json', data)


